import { SelectOption } from '@/types';

export const COLORS: SelectOption[] = [
  { value: 'Azul', label: 'Azul' },
  { value: 'Azul BB', label: 'Azul BB' },
  { value: 'Azul Marinho', label: 'Azul Marinho' },
  { value: 'Azul Cobalto', label: 'Azul Cobalto' },
  { value: 'Amarelo', label: 'Amarelo' },
  { value: 'Branco', label: 'Branco' },
  { value: 'Bege', label: 'Bege' },
  { value: 'Bordô', label: 'Bordô' },
  { value: 'Cinza', label: 'Cinza' },
  { value: 'Coral', label: 'Coral' },
  { value: 'Floral', label: 'Floral' },
  { value: 'Laranja', label: 'Laranja' },
  { value: 'Listrado', label: 'Listrado' },
  { value: 'Marrom', label: 'Marrom' },
  { value: 'Marsala', label: 'Marsala' },
  { value: 'Nude', label: 'Nude' },
  { value: 'Onça', label: 'Onça' },
  { value: 'OffWhite', label: 'OffWhite' },
  { value: 'Preto', label: 'Preto' },
  { value: 'Rosa', label: 'Rosa' },
  { value: 'Rosa Claro', label: 'Rosa Claro' },
  { value: 'Rosa BB', label: 'Rosa BB' },
  { value: 'Roxo', label: 'Roxo' },
  { value: 'Terracota', label: 'Terracota' },
  { value: 'Verde', label: 'Verde' },
  { value: 'Vermelho', label: 'Vermelho' },
  { value: 'Verde Água', label: 'Verde Água' },
  // Adicione mais conforme necessário
];